name: 构建并部署

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main

      - name: 配置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 配置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: 安装依赖
        run: pnpm install

      - name: 构建项目
        run: pnpm build

      - name: 创建 CNAME 文件
        run: echo "mcleng.cn" > ./dist/CNAME

      - name: 部署 dist 到 mcmineleng/blog
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: mcmineleng/blog
          publish_branch: main   # 或 gh-pages
          publish_dir: ./dist
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          commit_message: "chore: update dist from source repo"
